name: artigo
description: Artigo

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  get: ^4.6.1
  firebase_core: ^1.10.6
  firebase_auth: ^3.3.5
  firebase_database: ^8.2.0
  firebase_storage: ^10.2.5
  google_sign_in: ^5.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf